OLMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("books/", include("books.urls")),
    path("auth/", include("authentication.urls")),
]

books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path('',views.BookListView.as_view(),name='book_list'),
    path('<int:pk>',views.BookDetailView.as_view(),name='book_detail'),
    path('issue',views.book_issue,name='book_issue'),
    path('<int:pk>/borrow', views.book_borrow, name='book_borrow'),

]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "core"

urlpatterns = [
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('profile/update', views.profile_update, name='profile_update'),
    path('profile/picture/update', views.profile_picture_update, name='profile_picture_update'),
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/students', views.StudentListView.as_view(), name='dashboard_students_list'),
    path('dashboard/students/<int:pk>/delete',
         views.student_delete, name='dashboard_student_delete'),
    path('dashboard/books', views.BookListView.as_view(), name='dashboard_books_list'),
    path('dashboard/books/add', views.BookCreateView.as_view(),
         name='dashboard_book_create_form'),
    path('dashboard/books/<int:pk>/delete',
         views.book_delete, name='dashboard_book_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from datetime import (timedelta, datetime)
from core.models import Profile
# Create your models here.

class Book(models.Model):
    image = models.ImageField(blank=False, upload_to='images/book/')
    title = models.CharField(max_length=150)
    description = models.TextField()
    author = models.CharField(max_length=80)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title


def due_date():
    return datetime.today() + timedelta(days=14)


class BookIssue(models.Model):

    student = models.ForeignKey(Profile, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    issue_date = models.DateField(auto_now=True)
    due_date = models.DateField(default=due_date())
    borrow_date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"This book is issued by {self.student.user.username}"

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    picture = models.ImageField(
        blank=True, null=True, upload_to=f'images/profile/')
    fines = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.user.username

books/forms.py
from django import forms
from .models import (BookIssue)


class BookIssueForm(forms.ModelForm):
    class Meta:
        model=BookIssue
        fields = ['book','student','borrow_date']

core/forms.py
from django import forms
from django.contrib.auth.models import User
from core.models import Profile
from books.models import Book


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['picture']

    def clean_picture(self):
        picture = self.cleaned_data['picture']
        if picture:
            return picture


class UserForm(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.CharField(required=False)
    username = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_email(self):
        email = self.cleaned_data['email']
        if email:
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError("A user with this email already exists.")
            return email
        else:
            return None

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'image', 'quantity']

books/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import (ListView, DetailView)
from .models import (Book, BookIssue)
from django.http import (HttpRequest, JsonResponse, HttpResponseRedirect)
from django.views.decorators.csrf import csrf_exempt
from .forms import (BookIssueForm)
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http.request import QueryDict
from django.http import Http404
from django.contrib import messages
from datetime import datetime
# Create your views here.


class BookListView(ListView):
    template_name = 'books/book_list.html'
    model = Book
    context_object_name = 'book_list'


class BookDetailView(DetailView):
    template_name = 'books/book_detail.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issued'] = BookIssue.objects.filter(
            book=self.kwargs['pk'], student=self.request.user.id, borrow_date=None).exists()
        return context


@csrf_exempt
def book_borrow(request: HttpRequest, pk):
    try:
        issue_book = get_object_or_404(BookIssue, pk=pk)
        days = datetime.today().date()-issue_book.issue_date
        d = days.days
        fine = 0
        if d > 14:
            day = d-14
            fine = day*5
        issue_book.student.fines += fine
        issue_book.student.save()
        issue_book.borrow_date = datetime.now()
        issue_book.book.quantity += 1
        issue_book.book.save()
        issue_book.save()
        messages.success(request, f'You have borrowed {issue_book.book.title}')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except ObjectDoesNotExist:
        return Http404


@csrf_exempt
def book_issue(request: HttpRequest):
    try:
        if request.user.is_authenticated:
            if request.user.groups.filter(name="admin").exists():
                raise ValidationError('Cannot issue a book for an admin')
            if request.method == 'POST':
                post = QueryDict(mutable=True)
                post.appendlist('book', request.POST['book'])
                post.appendlist('student', request.user.id)
                form = BookIssueForm(post)
                if form.is_valid():
                    issue_book = form.save(commit=False)
                    if issue_book.book.quantity > 0:
                        issue_book.book.quantity -= 1
                        issue_book.book.save()
                    issue_book.save()
                    return JsonResponse({'status': 'success', 'message': 'Book issued successfully'})
                else:
                    raise ValidationError(form.errors.as_json())
        else:
            raise ValidationError('You must be logged in to issue books')
    except ValidationError as e:
        return JsonResponse({'status': 'error', 'error': e.messages})

core/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (ListView, TemplateView, CreateView)
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User, Group
from django.http import (HttpRequest, JsonResponse,
                         Http404, HttpResponseRedirect)
from core.forms import (BookForm, UserForm, ProfileForm)
from django.core.exceptions import (ValidationError, ObjectDoesNotExist)
from django.contrib.auth.decorators import (login_required)
from authentication.utils import group_required
from books.models import (Book, BookIssue)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from books.models import (BookIssue)


# Create your views here.
@method_decorator([login_required(login_url=reverse_lazy('login'))], name='dispatch')
class ProfileView(TemplateView):
    template_name = 'core/profile/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issues_books_list'] = BookIssue.objects.filter(
            student=self.request.user.id, borrow_date=None)
        return context


@csrf_exempt
def profile_picture_update(request: HttpRequest):
    try:
        if request.method == 'POST':
            if request.user.is_authenticated:
                profile_form = ProfileForm(
                    files=request.FILES, instance=request.user.profile)
                if profile_form.is_valid():
                    profile_form.save()
                    return JsonResponse({'status': 'success', "message": "Profile picture updated"})
                else:
                    raise ValidationError(profile_form.errors)
            else:
                return JsonResponse({"status": "error", "error": ["You must be logged in to update your profile picture"]}, status=401)
        else:
            return HttpResponseRedirect(reverse_lazy('core:profile'))
    except ValidationError as error:
        return JsonResponse({"status": "error", "error": error.messages})


@csrf_exempt
def profile_update(request: HttpRequest):
    try:
        if request.method == 'POST':
            if request.user.is_authenticated:
                user_form = UserForm(request.POST)
                if user_form.is_valid():
                    user = request.user
                    user.email = user_form.cleaned_data['email'] or user.email
                    user.first_name = user_form.cleaned_data['first_name'] or user.first_name
                    user.last_name = user_form.cleaned_data['last_name'] or user.last_name
                    user.username = user_form.cleaned_data['username'] or user.username
                    user.save()
                    return JsonResponse({'status': 'success', "data": {
                        "email": user.email,
                        "username": user.username,
                        "first_name": user.first_name,
                        "last_name": user.last_name,
                    }})
                else:
                    raise ValidationError(user_form.errors.as_json())
            else:
                return JsonResponse({"status": "error", "error": ["You must be logged in to update your profile"]}, status=401)
        else:
            return HttpResponseRedirect(reverse_lazy('core:profile'))
    except ValidationError as error:
        return JsonResponse({"status": "error", "error": error.messages}, status=401)


@method_decorator([login_required(login_url=reverse_lazy('login')), group_required(['admin'], login_url=reverse_lazy('login'))], name='dispatch')
class DashboardView(TemplateView):
    template_name = 'core/dashboard/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_books'] = Book.objects.all().count()
        context['total_issue_books'] = BookIssue.objects.all().count()
        context['total_students'] = User.objects.filter(is_superuser=False, is_staff=False,
                                                        ).exclude(groups=(Group.objects.get(name="admin").pk)).count()
        return context


@method_decorator([login_required(login_url=reverse_lazy('login')), group_required(['admin'], login_url=reverse_lazy('login'))], name='dispatch')
class StudentListView(ListView):
    template_name = 'core/dashboard/students_list.html'
    context_object_name = 'students_list'

    def get_queryset(self):
        return User.objects.filter(is_superuser=False, is_staff=False,
                                   ).exclude(groups=(Group.objects.get(name="admin").pk))


@group_required(['admin'], login_url=reverse_lazy('login'))
@login_required(login_url=reverse_lazy('login'))
def student_delete(request: HttpRequest, pk: int):
    try:
        student = get_object_or_404(User, pk=pk)
        student.delete()
        messages.success(request, 'Student has been successfully deleted')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except ObjectDoesNotExist:
        return Http404("Student does not exist")


@method_decorator([login_required(login_url=reverse_lazy('login')), group_required(['admin'], login_url=reverse_lazy('login'))], name='dispatch')
class BookListView(ListView):
    template_name = 'core/dashboard/books_list.html'
    context_object_name = 'books_list'
    model = Book


@group_required(['admin'], login_url=reverse_lazy('login'))
@login_required(login_url=reverse_lazy('login'))
def book_delete(request: HttpRequest, pk: int):
    try:
        book = get_object_or_404(Book, pk=pk)
        book.delete()
        messages.success(request, 'Book has been successfully deleted')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except ObjectDoesNotExist:
        return Http404("Book does not exist")


@method_decorator([login_required(login_url=reverse_lazy('login')), group_required(['admin'], login_url=reverse_lazy('login'))], name='dispatch')
class BookCreateView(SuccessMessageMixin, CreateView):
    template_name = 'core/dashboard/book_form.html'
    form_class = BookForm
    success_url = reverse_lazy('core:dashboard_book_create_form')
    success_message = "Book has been successfully created"

core/templates/core/dashboard/book_form.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">Add Book</div>
    <div class="card-body">
        <form method="post" id="add-book-form" class="form-group" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Start from row no 1 -->
            <div class="row mb-3">
                <div class="col">
                    <label class="form-label">Image</label>
                    <input type="file" id="imageInput"
                        class="form-control {% if form.image.errors %}is-invalid {% endif %}" name="image"
                        accept="image/*" />
                    {% if form.errors.image %} <span
                        class='image invalid-feedback'>{{ form.errors.image|first }}</span>{% endif %}
                </div>
            </div>
            <!-- End from row no 1 -->
            <!-- Start from row no 2 -->
            <div class="row mb-3">
                <div class="col">
                    <label class="form-label">Title</label>
                    <input type="text" id="titleInput"
                        class="form-control {% if form.title.errors %}is-invalid {% endif %}" placeholder="Book title"
                        name="title" />
                    {% if form.errors.title %} <span
                        class='title invalid-feedback'>{{ form.errors.title|first }}</span>{% endif %}
                </div>
            </div>
            <!-- End from row no 2 -->
            <!-- Start from row no 3 -->
            <div class="row mb-3">
                <div class="col">
                    <label class="form-label">Description </label>
                    <textarea id="descriptionInput"
                        class="form-control {% if form.description.errors %}is-invalid {% endif %}"
                        placeholder="Book description" name="description" rows="5"></textarea>
                    {% if form.errors.description %} <span
                        class='description invalid-feedback'>{{ form.errors.description|first }}</span>{% endif %}
                </div>
            </div>
            <!-- End from row no 3 -->
            <!-- Start from row no 4 -->
            <div class="row mb-3">
                <div class="col">
                    <label class="form-label">Author</label>
                    <input type="text" id="authorInput"
                        class="form-control {% if form.author.errors %}is-invalid {% endif %}" placeholder="Book Author"
                        name="author" />
                    {% if form.errors.author %} <span
                        class='author invalid-feedback'>{{ form.errors.author|first }}</span>{% endif %}
                </div>
            </div>
            <!-- End form row no 4 -->
            <!-- Start from row no 5 -->
            <div class="row mb-3">
                <div class="col">
                    <label class="form-label">Quantity</label>
                    <input type="number" id="quantityInput"
                        class="form-control {% if form.quantity.errors %}is-invalid {% endif %}"
                        placeholder="Book Quantity" name="quantity" />
                    {% if form.errors.quantity %} <span
                        class='quantity invalid-feedback'>{{ form.errors.quantity|first }}</span>{% endif %}
                </div>
            </div>
            <!-- End form row no 5 -->
            <!-- Start form row no 6 -->
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-primary">
                    Add new book
                </button>
                <a href="{% url 'core:dashboard_books_list' %}" class="btn btn-secondary">
                    Cancel
                </a>
            </div>
            <!-- End from row no 6 -->
        </form>
    </div>
</div>
{% endblock content %}

core/templates/core/dashboard/books_list.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'core:dashboard_book_create_form' %}" class="btn btn-primary mb-3"><i class="fa fa-plus"></i>&nbsp;Add Book</a>
<table id="dataTable" class="table table-striped" style="width: 100%">
    <thead>
        <tr>
            <th scope="row">ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Author</th>
            <th>In Stock</th>
            <th>Issued</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books_list %}
        <tr>
            <th scope="row">{{ book.id }}</th>
            <td>{{ book.title }}</td>
            <td>{{ book.description }}</td>
            <td>{{ book.author }}</td>
            <td>{{ book.quantity }}</td>
            <td>2013-08-11</td>
            <td class="">
                <a href="{% url 'core:dashboard_book_delete' book.id %}" onclick="confirm('Are you sure?')" class="text-danger"><i
                        class="fa fa-trash"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

core/templates/core/dashboard/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-6 col-sm-6 mb-3">
        <div class="card text-dark bg-warning">
            <h5 class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="title">Students</div>
                    <div class="toggle-icon" style="cursor: pointer">
                        <i class="fas fa-minus"></i>
                    </div>
                </div>
            </h5>
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm-12">
                        <a href="{% url 'core:dashboard_students_list' %}" class="btn w-100 btn-dark"><i class="fa fa-list"></i></a>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-sm-12">
                        <div class="d-flex justify-content-between">
                            <strong>Total Students</strong>
                            <div>{{ total_students }}</div>
                        </div>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-sm-12">
                        <div class="d-flex justify-content-between">
                            <strong>Issued</strong>
                            <div>20</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-sm-6 mb-3">
        <div class="card text-light bg-dark">
            <h5 class="card-header">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="title">Books</div>
                    <div class="toggle-icon" style="cursor: pointer">
                        <i class="fa fa-minus"></i>
                    </div>
                </div>
            </h5>
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <a href="{% url 'core:dashboard_book_create_form' %}" class="btn w-100 btn-warning"><i class="fa fa-plus"></i></a>
                    </div>
                    <div class="col-sm-6">
                        <a href="{% url 'core:dashboard_books_list' %}" class="btn w-100 btn-warning"><i class="fa fa-list"></i></a>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-sm-12">
                        <div class="d-flex justify-content-between">
                            <strong>Total Books</strong>
                            <div>{{ total_books }}</div>
                        </div>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-sm-12">
                        <div class="d-flex justify-content-between">
                            <strong>Issued</strong>
                            <div>{{ total_issue_books }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/core/dashboard/students_list.html
{% extends 'base.html' %}

{% block content %}
<table id="dataTable" class="table table-responsive table-striped" style="width: 100%">
    <thead>
        <tr>
            <th scope="row">ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Fines</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students_list %}
        <tr>
            <th scope="row">{{ student.id }}</th>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.username }}</td>
            <td>{{ student.email }}</td>
            <td>${{ student.profile.fines }}</td>
            <td>
                <a href="{% url 'core:dashboard_student_delete' student.id %}" onclick="confirm('Are you sure?')" class="text-danger"><i class="fa fa-trash"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}