OLMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("books/", include("books.urls")),
    path("auth/", include("authentication.urls")),
]

books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path('',views.BookListView.as_view(),name='book_list'),
    path('<int:pk>',views.BookDetailView.as_view(),name='book_detail'),
    path('issue',views.book_issue,name='book_issue'),
    path('<int:pk>/borrow', views.book_borrow, name='book_borrow'),

]

books/models.py
from django.db import models
from datetime import (timedelta, datetime)
from core.models import Profile
# Create your models here.

class Book(models.Model):
    image = models.ImageField(blank=False, upload_to='images/book/')
    title = models.CharField(max_length=150)
    description = models.TextField()
    author = models.CharField(max_length=80)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title


def due_date():
    return datetime.today() + timedelta(days=14)


class BookIssue(models.Model):

    student = models.ForeignKey(Profile, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    issue_date = models.DateField(auto_now=True)
    due_date = models.DateField(default=due_date())
    borrow_date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"This book is issued by {self.student.user.username}"

books/forms.py
from django import forms
from .models import (BookIssue)


class BookIssueForm(forms.ModelForm):
    class Meta:
        model=BookIssue
        fields = ['book','student','borrow_date']

books/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import (ListView, DetailView)
from .models import (Book, BookIssue)
from django.http import (HttpRequest, JsonResponse, HttpResponseRedirect)
from django.views.decorators.csrf import csrf_exempt
from .forms import (BookIssueForm)
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.http.request import QueryDict
from django.http import Http404
from django.contrib import messages
from datetime import datetime
# Create your views here.


class BookListView(ListView):
    template_name = 'books/book_list.html'
    model = Book
    context_object_name = 'book_list'


class BookDetailView(DetailView):
    template_name = 'books/book_detail.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issued'] = BookIssue.objects.filter(
            book=self.kwargs['pk'], student=self.request.user.id, borrow_date=None).exists()
        return context


@csrf_exempt
def book_borrow(request: HttpRequest, pk):
    try:
        issue_book = get_object_or_404(BookIssue, pk=pk)
        days = datetime.today().date()-issue_book.issue_date
        d = days.days
        fine = 0
        if d > 14:
            day = d-14
            fine = day*5
        issue_book.student.fines += fine
        issue_book.student.save()
        issue_book.borrow_date = datetime.now()
        issue_book.book.quantity += 1
        issue_book.book.save()
        issue_book.save()
        messages.success(request, f'You have borrowed {issue_book.book.title}')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except ObjectDoesNotExist:
        return Http404


@csrf_exempt
def book_issue(request: HttpRequest):
    try:
        if request.user.is_authenticated:
            if request.user.groups.filter(name="admin").exists():
                raise ValidationError('Cannot issue a book for an admin')
            if request.method == 'POST':
                post = QueryDict(mutable=True)
                post.appendlist('book', request.POST['book'])
                post.appendlist('student', request.user.id)
                form = BookIssueForm(post)
                if form.is_valid():
                    issue_book = form.save(commit=False)
                    if issue_book.book.quantity > 0:
                        issue_book.book.quantity -= 1
                        issue_book.book.save()
                    issue_book.save()
                    return JsonResponse({'status': 'success', 'message': 'Book issued successfully'})
                else:
                    raise ValidationError(form.errors.as_json())
        else:
            raise ValidationError('You must be logged in to issue books')
    except ValidationError as e:
        return JsonResponse({'status': 'error', 'error': e.messages})

books/templates/books/book_detail.html
{% extends 'base.html' %}
{% load auth_check %}
{% block content %}
<div class="row">
    <div class="col-sm-5 mb-5">
        <img src="{{ book.image.url }}" alt="{{ book.title }}" width="100%" height="500px" />
    </div>
    <div class="col-sm-7">
        <div class="row mb-4">
            <h5>{{ book.title }}</h5>
        </div>
        <div class="row mb-4">
            <div>
                {{ book.description }}
            </div>
        </div>
        <div class="row mb-4">
            <div>
                <strong>Available:</strong>
                <span class="text-muted">{{ book.quantity }}</span>
            </div>
        </div>
        <div class="row mb-4">
            <div>
                <strong>Author:</strong>
                <span class="text-muted">{{ book.author }}</span>
            </div>
        </div>
        <div id="issue" class="row mb-4">
            {% if user.is_authenticated %}
                {% if book.quantity == 0 %}
                <p class="alert text-center alert-secondray">
                    This book is not available
                </p>
                {% elif user|has_group:"admin" %}
                <p class="alert text-center alert-warning">
                    Cannot issue a book for an admin
                </p>
                {% elif not issued %}
                <a href="{% url 'books:book_issue' %}" data-id="{{ book.id }}" id="issue-btn" class="btn w-100 btn-secondary">
                    Issue
                </a>
                {% else %}
                <p class="alert text-center alert-info">
                    You already have an issue with this book
                </p>
                {% endif %}
            {% else %}
            <a href="{% url 'login' %}?next={{ request.get_full_path }}" class="btn w-100 btn-secondary">
                Login to issue
            </a>
            {% endif %}

        </div>
    </div>
</div>
{% endblock content%}

books/templates/books/book_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    {% for book in book_list %}
    <div class="col-xl-3 col-md-4 col-sm-4">
        <div class="card">
            <a href="{% url 'books:book_detail' book.id %}">
                <img src="{{ book.image.url }}" height="250px" width="100%" alt="{{ book.title }}" />
            </a>
            <div class="card-body">
                <h5 class="card-title">
                    <div class="d-flex justify-content-between align-items-center">
                        <p>{{ book.title }}</p>
                    </div>
                </h5>

                <p class="card-text book-description">
                    {{ book.description }}
                </p>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="text-center">No there any book for now</div>
    {% endfor %}

</div>
{% endblock content%}