OLMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("books/", include("books.urls")),
    path("auth/", include("authentication.urls")),
]

books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path('',views.BookListView.as_view(),name='book_list'),
    path('<int:pk>',views.BookDetailView.as_view(),name='book_detail'),
    path('issue',views.book_issue,name='book_issue'),
    path('<int:pk>/borrow', views.book_borrow, name='book_borrow'),

]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "core"

urlpatterns = [
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('profile/update', views.profile_update, name='profile_update'),
    path('profile/picture/update', views.profile_picture_update, name='profile_picture_update'),
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/students', views.StudentListView.as_view(), name='dashboard_students_list'),
    path('dashboard/students/<int:pk>/delete',
         views.student_delete, name='dashboard_student_delete'),
    path('dashboard/books', views.BookListView.as_view(), name='dashboard_books_list'),
    path('dashboard/books/add', views.BookCreateView.as_view(),
         name='dashboard_book_create_form'),
    path('dashboard/books/<int:pk>/delete',
         views.book_delete, name='dashboard_book_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    picture = models.ImageField(
        blank=True, null=True, upload_to=f'images/profile/')
    fines = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.user.username

core/forms.py
from django import forms
from django.contrib.auth.models import User
from core.models import Profile
from books.models import Book


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['picture']

    def clean_picture(self):
        picture = self.cleaned_data['picture']
        if picture:
            return picture


class UserForm(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.CharField(required=False)
    username = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_email(self):
        email = self.cleaned_data['email']
        if email:
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError("A user with this email already exists.")
            return email
        else:
            return None

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description', 'image', 'quantity']

core/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (ListView, TemplateView, CreateView)
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User, Group
from django.http import (HttpRequest, JsonResponse,
                         Http404, HttpResponseRedirect)
from core.forms import (BookForm, UserForm, ProfileForm)
from django.core.exceptions import (ValidationError, ObjectDoesNotExist)
from django.contrib.auth.decorators import (login_required)
from authentication.utils import group_required
from books.models import (Book, BookIssue)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from books.models import (BookIssue)


# Create your views here.
@method_decorator([login_required(login_url=reverse_lazy('login'))], name='dispatch')
class ProfileView(TemplateView):
    template_name = 'core/profile/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issues_books_list'] = BookIssue.objects.filter(
            student=self.request.user.id, borrow_date=None)
        return context


@csrf_exempt
def profile_picture_update(request: HttpRequest):
    try:
        if request.method == 'POST':
            if request.user.is_authenticated:
                profile_form = ProfileForm(
                    files=request.FILES, instance=request.user.profile)
                if profile_form.is_valid():
                    profile_form.save()
                    return JsonResponse({'status': 'success', "message": "Profile picture updated"})
                else:
                    raise ValidationError(profile_form.errors)
            else:
                return JsonResponse({"status": "error", "error": ["You must be logged in to update your profile picture"]}, status=401)
        else:
            return HttpResponseRedirect(reverse_lazy('core:profile'))
    except ValidationError as error:
        return JsonResponse({"status": "error", "error": error.messages})


@csrf_exempt
def profile_update(request: HttpRequest):
    try:
        if request.method == 'POST':
            if request.user.is_authenticated:
                user_form = UserForm(request.POST)
                if user_form.is_valid():
                    user = request.user
                    user.email = user_form.cleaned_data['email'] or user.email
                    user.first_name = user_form.cleaned_data['first_name'] or user.first_name
                    user.last_name = user_form.cleaned_data['last_name'] or user.last_name
                    user.username = user_form.cleaned_data['username'] or user.username
                    user.save()
                    return JsonResponse({'status': 'success', "data": {
                        "email": user.email,
                        "username": user.username,
                        "first_name": user.first_name,
                        "last_name": user.last_name,
                    }})
                else:
                    raise ValidationError(user_form.errors.as_json())
            else:
                return JsonResponse({"status": "error", "error": ["You must be logged in to update your profile"]}, status=401)
        else:
            return HttpResponseRedirect(reverse_lazy('core:profile'))
    except ValidationError as error:
        return JsonResponse({"status": "error", "error": error.messages}, status=401)


@method_decorator([login_required(login_url=reverse_lazy('login')), group_required(['admin'], login_url=reverse_lazy('login'))], name='dispatch')
class DashboardView(TemplateView):
    template_name = 'core/dashboard/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_books'] = Book.objects.all().count()
        context['total_issue_books'] = BookIssue.objects.all().count()
        context['total_students'] = User.objects.filter(is_superuser=False, is_staff=False,
                                                        ).exclude(groups=(Group.objects.get(name="admin").pk)).count()
        return context


@method_decorator([login_required(login_url=reverse_lazy('login')), group_required(['admin'], login_url=reverse_lazy('login'))], name='dispatch')
class StudentListView(ListView):
    template_name = 'core/dashboard/students_list.html'
    context_object_name = 'students_list'

    def get_queryset(self):
        return User.objects.filter(is_superuser=False, is_staff=False,
                                   ).exclude(groups=(Group.objects.get(name="admin").pk))


@group_required(['admin'], login_url=reverse_lazy('login'))
@login_required(login_url=reverse_lazy('login'))
def student_delete(request: HttpRequest, pk: int):
    try:
        student = get_object_or_404(User, pk=pk)
        student.delete()
        messages.success(request, 'Student has been successfully deleted')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except ObjectDoesNotExist:
        return Http404("Student does not exist")


@method_decorator([login_required(login_url=reverse_lazy('login')), group_required(['admin'], login_url=reverse_lazy('login'))], name='dispatch')
class BookListView(ListView):
    template_name = 'core/dashboard/books_list.html'
    context_object_name = 'books_list'
    model = Book


@group_required(['admin'], login_url=reverse_lazy('login'))
@login_required(login_url=reverse_lazy('login'))
def book_delete(request: HttpRequest, pk: int):
    try:
        book = get_object_or_404(Book, pk=pk)
        book.delete()
        messages.success(request, 'Book has been successfully deleted')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except ObjectDoesNotExist:
        return Http404("Book does not exist")


@method_decorator([login_required(login_url=reverse_lazy('login')), group_required(['admin'], login_url=reverse_lazy('login'))], name='dispatch')
class BookCreateView(SuccessMessageMixin, CreateView):
    template_name = 'core/dashboard/book_form.html'
    form_class = BookForm
    success_url = reverse_lazy('core:dashboard_book_create_form')
    success_message = "Book has been successfully created"

core/templates/core/partials/footer.html
{% load static %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/toastify.min.js' %}"></script>
<script src="{% static 'js/query.min.js' %}"></script>
<script src="{% static 'js/datatables.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% if messages %}
{% for message in messages %}
{% if message.level == 25 %}
<script type="text/javascript">
    $(() => {
        Toastify({
            text: "{{ message }}",
            duration: 3000,
            newWindow: true,
            close: true,
            gravity: "top", // `top` or `bottom`
            position: "center", // `left`, `center` or `right`
            stopOnFocus: true, // Prevents dismissing of toast on hover
            style: {
                background: "#32CD32",
            },
        }).showToast();
    });
</script>
{% endif %}
{% if message.level == 40 %}
<script type="text/javascript">
    $(() => {
        Toastify({
            text: "{{ message }}",
            duration: 3000,
            newWindow: true,
            close: true,
            gravity: "top", // `top` or `bottom`
            position: "center", // `left`, `center` or `right`
            stopOnFocus: true, // Prevents dismissing of toast on hover
            style: {
                background: "#FF5349",
            },
        }).showToast();
    });
</script>
{% endif %}
{% endfor %}
{% endif %}
</body>

</html>

core/templates/core/partials/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Online Library Management System </title>

        <link rel="stylesheet" href="{% static 'css/main.css' %}" />
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

    </head>

    <body>

core/templates/core/partials/navbar.html
{% load auth_check %}
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container justify-content-between">
            <a class="navbar-brand" href="{% url 'core:home' %}">Online Library Management System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse justify-content-end navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'books:book_list' %}">Books</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="{% url 'core:profile' %}">My Profile</a>
                            </li>
                            {% if user|has_group:"admin" %}
                            <li>
                                <a class="dropdown-item" href="{% url 'core:dashboard' %}">Dashboard</a>
                            </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </li>
                        </ul>
                    </li>

                </ul>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
            </div>
        </div>
    </nav>
</header>